name = "ma-malnu-kananga"
main = "dist/_worker.js"
compatibility_date = "2024-09-02"

[site]
bucket = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ma-malnu-kananga-db"

[vars]
NEWS_SOURCES = "https://kemenag.go.id/rss,https://madrasah.kemenag.go.id/feed"
SCHOLARSHIP_SOURCES = "https://www.kemdikbud.go.id/main/blog/category/Beasiswa/feed"
